package entity;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
import java.util.List;

public class ForumComment {
    private Integer iscomment;
    private User user=null;
    private List<ForumComment> reply=null;

    public List<ForumComment> getReply() {
        return reply;
    }

    public void setReply(List<ForumComment> reply) {
        this.reply = reply;
    }

    @Override
    public String toString() {
        return "ForumComment{" +
                "iscomment=" + iscomment +
                ", user=" + user +
                ", commentid=" + commentid +
                ", uid=" + uid +
                ", forumid=" + forumid +
                ", date=" + date +
                ", content='" + content + '\'' +
                '}';
    }

    public Integer getIscomment() {
        return iscomment;
    }

    public void setIscomment(Integer iscomment) {
        this.iscomment = iscomment;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_comment.commentid
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    private Integer commentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_comment.uid
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_comment.forumid
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    private Integer forumid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_comment.date
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_comment.content
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_comment.commentid
     *
     * @return the value of forum_comment.commentid
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_comment.commentid
     *
     * @param commentid the value for forum_comment.commentid
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_comment.uid
     *
     * @return the value of forum_comment.uid
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_comment.uid
     *
     * @param uid the value for forum_comment.uid
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_comment.forumid
     *
     * @return the value of forum_comment.forumid
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public Integer getForumid() {
        return forumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_comment.forumid
     *
     * @param forumid the value for forum_comment.forumid
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public void setForumid(Integer forumid) {
        this.forumid = forumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_comment.date
     *
     * @return the value of forum_comment.date
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_comment.date
     *
     * @param date the value for forum_comment.date
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_comment.content
     *
     * @return the value of forum_comment.content
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_comment.content
     *
     * @param content the value for forum_comment.content
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}