package entity;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
import java.util.List;

public class SkillComment {

    private Integer commentid;
    private Integer uid;
    private Integer skillid;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date date;
    private String content;
    private Integer iscomment;
    private User user=null;
    private List<SkillComment> reply=null;

    public List<SkillComment> getReply() {
        return reply;
    }

    public void setReply(List<SkillComment> reply) {
        this.reply = reply;
    }

    @Override
    public String toString() {
        return "SkillComment{" +
                "commentid=" + commentid +
                ", uid=" + uid +
                ", skillid=" + skillid +
                ", date=" + date +
                ", content='" + content + '\'' +
                ", iscomment=" + iscomment +
                ", user=" + user +
                '}';
    }

    public Integer getIscomment() {
        return iscomment;
    }

    public void setIscomment(Integer iscomment) {
        this.iscomment = iscomment;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Integer getCommentid() {
        return commentid;
    }
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_comment.uid
     *
     * @param uid the value for skill_comment.uid
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_comment.skillid
     *
     * @return the value of skill_comment.skillid
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public Integer getSkillid() {
        return skillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_comment.skillid
     *
     * @param skillid the value for skill_comment.skillid
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public void setSkillid(Integer skillid) {
        this.skillid = skillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_comment.date
     *
     * @return the value of skill_comment.date
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_comment.date
     *
     * @param date the value for skill_comment.date
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_comment.content
     *
     * @return the value of skill_comment.content
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_comment.content
     *
     * @param content the value for skill_comment.content
     *
     * @mbg.generated Wed May 27 14:21:21 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}